// <auto-generated />
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("item_code");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("barcode");

                    b.Property<string>("CustomerDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("customer_description");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<int>("ManageItemBy")
                        .HasColumnType("int")
                        .HasColumnName("manage_item_by");

                    b.Property<decimal>("MaximumInventory")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maximum_inventory");

                    b.Property<decimal>("MinimumInventory")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("minimum_inventory");

                    b.Property<bool>("PurchasedItem")
                        .HasColumnType("bit")
                        .HasColumnName("purchased_item");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<bool>("SalesItem")
                        .HasColumnType("bit")
                        .HasColumnName("sales_item");

                    b.Property<bool>("StockItem")
                        .HasColumnType("bit")
                        .HasColumnName("stock_item");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
